name: jhentai
description: A flutter app for  EHentai

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.3
  cookie_jar: 3.0.1
  dio_cookie_manager: ^2.0.0
  dio_cache_interceptor: ^3.2.6
  dio_cache_interceptor_db_store: ^4.1.1
  get: ^4.3.8
  get_storage: ^2.0.3
  extended_nested_scroll_view: ^5.0.0
  flukit: ^2.0.0
  flutter_easyrefresh: ^2.2.1
  html: ^0.15.0
  logger: ^1.1.0
  flutter_rating_bar: ^4.0.0
  waterfall_flow: ^3.0.2
  extended_image: ^6.0.1
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  collection: 1.15.0
  clipboard: ^0.1.3
  flutter_list_view: ^1.1.9
  scrollable_positioned_list: ^0.2.3
  executor: ^2.2.2
  retry: ^3.1.0
  path: ^1.8.0
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.9
  flutter_slidable: ^1.2.0
  flutter_widget_from_html: ^0.8.5
  url_launcher: ^6.0.20
  like_button: ^2.0.4
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.19.5
  drift_dev: ^1.5.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
#  assets:
